name: CI/CD

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Pull Master Branch
      run: |
        cd /home/ubuntu/test/ && sudo git pull origin master
